BirdcageOntology/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BirdcageOntology/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class QueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Querie1()
        {
            return View();
        }

        public IActionResult Querie2()
        {
            return View();
        }
    }
}

BirdcageOntology/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Entities.Model;

namespace WebApp.Controllers
{
    public class SpeciesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }        

        [Route("viewspeciesdetail")]
        [HttpPost]
        public IActionResult ViewSpecie([FromBody] Bird bird)
        {
            return View(bird);
        }
    }
}

BirdcageOntology/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">About</h1>
    </div>
</div>
<div class="row" id="panel_generalInfo">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div>
                    <font size="3">
                        Learn about  Panama Nest
                    </font>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div>
                <div class="row" style="margin-bottom:15px">
                    <div class="col-md-6">
                        <div class="row">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*Preguntas Colapsables*@

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" style="background:#F5F5F5 !important"><font color="black" size="5">What can be found on Panama Nest Ontology?</font></a>
            </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in" aria-expanded="true">
            <div class="panel-body">
                <font color="black" size="4">
                    The aviafauna of Panama includes a total of 987 species according to Bird Checklists of the World. Most of this species can be found all over America and even in other continents. As an small country, the number of species within Panama's territory is immense. <br />
                    This ontology will provide information about birds of different orders and families. The data handled by the ontology includes the taxonomic rank of the birds and other characteristics like size, habitat, and common name. <br /> <br />
                    You can search data about any bird or you can use other parameters like the family, or the gen. The ontology will show the result according to the information you have searched. You can also expand the ontology by creating new elements.
                </font>
            </div>
        </div>
    </div>
  
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="collapsed" aria-expanded="false" style="background:#F5F5F5 !important"><font color="black" size="5">Why choose an ontology?</font></a>
            </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse" aria-expanded="false">
            <div class="panel-body">
                <font color="black" size="4">
                    In order to maintain structured information on a web application you can use Semantic Web.
                    This can be defined as an extension of the Worldwide Web that contains information with explicit meaning  making it easier for machines to automatically process and integrate information available on the Web.
                    <br /> <br /> Semantic Web make use of many tools as vocabularies and ontologies to fullfill this goal. Ontologies
                    allow users to clasify content (like a taxonomy) which allows you to relate data based on the information in it as opposed to a term describing it. <br />
                    <br />This represents great value for organizatios because it allows to:

                    <ul>
                        <br />
                        <li>Manage content more effectively.</li>
                        <li>Maximize findability and discoverability of information.</li>
                        <li>Increase the reuse of “hidden” and unknown information.</li>
                        <li>Elevate SEO on external search engines.</li>
                    </ul>
                </font>
            </div>
        </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse3" class="collapsed" aria-expanded="false" style="background:#F5F5F5 !important"><font color="black" size="5">Resources/Tools</font></a>
                </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse" aria-expanded="false">
                <div class="panel-body">
                    <font color="black" size="4">
                     We made use of different programming tools to achieve this project:
                        <ul>
                            <li>The ongology was created using Protege and The SPARQL Server, Apache Jena Fuseki to administrate querying, updating and the Graph Store.</li>
                            <li>This web application follows the MVC architectural pattern.</li>
                            <li>The programming languages implemented were C# and JavaScript.</li>
                        </ul>
                    </font>
                </div>
            </div>
            </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse4" class="collapsed" aria-expanded="false" style="background:#F5F5F5 !important"><font color="black" size="5">Academic Value</font></a>
            </h4>
        </div>
        <div id="collapse4" class="panel-collapse collapse" aria-expanded="false">
            <div class="panel-body">
                <font color="black" size="4">
                    This project could benefit investigators, scientists, students and people interested on birds. The idea of creating this project is to acquired knowledge about birds
                    and also to expand the data found on the ontology with sources of information from anywhere.
                    It could be a great tool for bird studies and also a way to teach undergraduate students about the taxonomic rank of birds and other characteristics assorted on the website.
                </font>
            </div>
        </div>
    </div>
    </div>

BirdcageOntology/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}


<div>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact</h1>
        </div>
    </div>
    <div>
        <img src="~/images/logo_utp.png" alt="UTP logo" style="margin-left:80px;margin-top:50px;width:400px;height:400px;float:left">

        <h3 style="margin-left:600px">Jackelin Chong</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                jackelin.chong@utp.ac.pa
            </div>
        </div>
        <h3 style="margin-left:600px">Iván Martínez</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                ivan.martinez1@utp.ac.pa
            </div>
        </div>
        <h3 style="margin-left:600px">Omar Mejía</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                omar.mejia@utp.ac.pa
            </div>
        </div>
        <h3 style="margin-left:600px">Gabriela Reyes</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                gabriela.reyes@utp.ac.pa
            </div>
        </div>
        <h3 style="margin-left:600px">Andrés Tuñón</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                andres.tuñon@utp.ac.pa
            </div>
        </div>
        <h3 style="margin-left:600px">Carlos Villareal</h3>
        <div style="margin-left:600px">
            <div style="margin-right:47px">
                Universidad Tecnológica de Panamá
                <br />
                carlos.villareal@utp.ac.pa
            </div>
        </div>
    </div>

</div>

BirdcageOntology/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        @*<li data-target="#myCarousel" data-slide-to="4"></li>*@

    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/bluebird.jpg" class="img-responsive" alt="Bluebird" style="width:100%;height:100%"/>
            <div class="carousel-caption" role="option">
                <h2>
                    <font color="white">The Panama Nest Ontology<br /></font>
                </h2>
            </div>
        </div>
        @*<div class="item">
            <img src="~/images/wetland.jpg" alt="Wetland" class="img-responsive" style="width:100%;height:100%" />
            <div class="carousel-caption" role="option">
               
            </div>
        </div>*@
        <div class="item">
            <img src="~/images/redguacamaya.jpg" alt="Guacamayas" class="img-responsive" style="width:100%;height:100%" />
            <div class="carousel-caption" role="option">
                <font color="white">
                    <h2>Query the Ontology </h2>
                    <p><font color="white">Use one of our predefined queries to search for our local birds</font></p>
                </font>
            </div>
        </div>
        <div class="item">
            <img src="~/images/birdband.jpg" alt="Bird Band" class="img-responsive" style="width:100%;height:100%" />
            <div class="carousel-caption" role="option">
                <font color="white">
                    <h2>Expand Our Database</h2>
                    <p><font color="white">Register new species in the Ontology</font></p>
                </font>
            </div>
        </div>    
        <div class="item">
            <img src="~/images/roundbird.jpg" alt="Microsoft Azure" class="img-responsive" style="width:100%;height:100%" />
            <div class="carousel-caption" role="option">
                <font color="white">
                    <h2>Learn More About This Project</h2>
                    <p><font color="white">Why use and ontology and the academic value behind it</font></p>
                </font>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row" style="margin-top:15px">
    <div class="col-md-4">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-pagelines fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">10</div>
                        <div>Species in Ontology</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index", "Species")">
                <div class="panel-footer">
                    <span class="pull-left">Add New Species</span>
                    <span class="pull-right">
                        <i class="fa fa-arrow-circle-right"></i>
                    </span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa  fa-search fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">2</div>
                        <div>Available Queries</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Querie1", "Query")">
                <div class="panel-footer">
                    <span class="pull-left">Filter by Bird Taxon</span>
                    <span class="pull-right">
                        <i class="fa fa-arrow-circle-right"></i>
                    </span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="@Url.Action("Querie2", "Query")">
                <div class="panel-footer">
                    <span class="pull-left">Filter by Bird Location</span>
                    <span class="pull-right">
                        <i class="fa fa-arrow-circle-right"></i>
                    </span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-group fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">*</div>
                        <div>Read More About This Project</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("About", "Home")">
                <div class="panel-footer">
                    <span class="pull-left">Why use an Ontology</span>
                    <span class="pull-right">
                        <i class="fa fa-arrow-circle-right"></i>
                    </span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

@*<div class="row" style="margin-top:50px;text-align:center">
    <div class="col-md-3">
        <a class="topic" href="Species">
            <!--referencia-->
            <div class="modal-content" style="background-color:lightskyblue">
                <h3 class="modal-title" style="margin-top:25px">Add</h3>
                <div class="fa fa-plus-square" style="font-size:50px">
                    <!--imagen del add-->
                </div>
                <div class="modal-body">
                    <p>
                        <font color="black">
                            Some text in the modal.
                        </font>
                    </p>
                </div>
            </div>
        </a> <!--fin de la referencia-->
    </div>

    <div class="col-md-3">
        <a class="topic" href="Species/ViewSpecie">
            <!--referencia-->
            <div class="modal-content" style="background-color:lightblue">
                <h3 class="modal-title" style="margin-top:25px">View</h3>
                <div class="fa fa-eye" style="font-size:50px">
                    <!--imagen del view-->
                </div>
                <div class="modal-body">
                    <p>
                        <font color="black">
                            Some text in the modal.
                        </font>
                    </p>
                </div>
            </div>
        </a> <!--fin de la referencia-->
    </div>

    <div class="col-md-3">
        <a class="topic" href="Query/Querie1">
            <!--referencia-->
            <div class="modal-content" style="background-color:darkred">
                <h3 class="modal-title" style="margin-top:25px">Query 1</h3>
                <div class="fa fa-search" style="font-size:50px">
                    <!--imagen del query-->
                </div>
                <div class="modal-body">
                    <p>
                        <font color="black">
                            Some text in the modal.
                        </font>
                    </p>
                </div>
            </div>
        </a> <!--fin de la referencia-->
    </div>

    <div class="col-md-3">
        <a class="topic" href="Query/Querie2">
            <!--referencia-->
            <div class="modal-content" style="background-color:#5bc0de">
                <h3 class="modal-title" style="margin-top:25px">Query 2</h3>
                <div class="fa fa-search" style="font-size:50px">
                    <!--imagen del query-->
                </div>
                <div class="modal-body">
                    <p>
                        <font color="black">
                            Some text in the modal.
                        </font>
                    </p>
                </div>
            </div>
        </a> <!--fin de la referencia-->
    </div>
</div>*@